/*
 */
package Programa;

import java.io.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Josué Vásquez
 */
public class ManejoArchivos extends javax.swing.JFrame {
    

    /**
     * Creates new form ManejoArchivos
     */
    public ManejoArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtImpresion = new javax.swing.JTextPane();
        bCrear = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bAnexar = new javax.swing.JButton();
        bVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("MANEJO DE ARCHIVOS");

        jScrollPane1.setViewportView(txtImpresion);

        bCrear.setText("CREAR");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bGuardar.setText("GUARDAR");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bAnexar.setText("ANEXAR");
        bAnexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnexarActionPerformed(evt);
            }
        });

        bVer.setText("VER");
        bVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtArchivo);

        jLabel2.setText("Nombre del Archivo");

        jLabel3.setText("Impresión / Vista Documento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bAnexar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bVer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bCrear)
                        .addGap(18, 18, 18)
                        .addComponent(bGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(bAnexar)
                        .addGap(18, 18, 18)
                        .addComponent(bVer)
                        .addGap(9, 9, 9)))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // CrearArchivo
        
        String Arch = (String)txtArchivo.getText();
        File archivo = new File ("c:\\PruebaJava\\"+ Arch +".txt");
        try
        {
            PrintWriter salida = new PrintWriter(new FileWriter(archivo));
            salida.close();
            JOptionPane.showMessageDialog(null, "El archivo se ha creado correctamente");
        }catch(IOException ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // Escribir o GuardarArchivo
        String Contenido = (String)txtImpresion.getText();
        String Arch = (String)txtArchivo.getText();
        File archivo = new File ("c:\\PruebaJava\\"+ Arch +".txt");
        try
        {
            PrintWriter salida = new PrintWriter(new FileWriter(archivo));
            salida.println(Contenido);
            salida.println();
            salida.close();
            JOptionPane.showMessageDialog(null,"Guardado,el contenido se ha escrito correctamente");
        }catch (IOException ex)
        {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bAnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnexarActionPerformed
        // Anexar Archivo
        String Anexar = (String)txtImpresion.getText();
        String Arch = (String)txtArchivo.getText();
        File archivo = new File ("c:\\PruebaJava\\"+ Arch +".txt");
        try
        {
            PrintWriter salida = new PrintWriter(new FileWriter(archivo,true));
            salida.println(Anexar);
            salida.println();
            salida.close();
            JOptionPane.showMessageDialog(null,"Cambios Guardados correctamente");
        }catch (IOException ex)
        {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_bAnexarActionPerformed

    private void bVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerActionPerformed
        //Leer Archivo
        String Arch = (String)txtArchivo.getText();
        File archivo = new File ("c:\\PruebaJava\\"+ Arch +".txt"); 
        try
        {
            BufferedReader entrada = new BufferedReader(new FileReader(archivo));
            String lectura;
            lectura = entrada.readLine();
            txtImpresion.setText(String.valueOf(lectura));
            entrada.close();
            JOptionPane.showMessageDialog(null,"Contenido Mostrado Correctamente");
        }catch (IOException ex)
        {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_bVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejoArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejoArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejoArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejoArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejoArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnexar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtArchivo;
    private javax.swing.JTextPane txtImpresion;
    // End of variables declaration//GEN-END:variables
}
